name: dbus
version: 0.2.0-nullsafety.0

description:
  A native Dart implementation of the D-Bus message bus client. This package
  allows Dart applications to directly access services on the Linux desktop.

homepage: https://github.com/canonical/dbus.dart

environment:
  sdk: '>=2.12.0-259.1.beta <3.0.0'

dependencies:
  args: ^2.0.0-nullsafety
  xml: ^5.0.0-nullsafety

dev_dependencies:
  pedantic: ^1.9.0

executables:
  dart-dbus:
